name = "FractionalDelayFilters"
uuid = "abb49f1b-40bb-4cc5-b33d-4e7046aee330"
authors = ["Roy <rwang013@uottawa.ca>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
